/**
 * undoStore.ts — Zustand store for the single active undo item.
 *
 * Mechanics (D-13, D-14, UI-SPEC § Undo toast):
 *   - Only ONE active undo item at a time. A second completion/delete replaces
 *     the first (last-action-wins). There is no array or queue.
 *   - When a new item replaces an old one, the old item's hard-delete fires
 *     immediately (before the undo window expires for the old item).
 *   - The 4-second countdown timer is managed externally (UndoToast component).
 *     The store holds the item reference; the component fires hardDeleteTask
 *     when the countdown expires or when it is superseded by a new show().
 *   - clear() is called when: the user clicks "Undo" (undo fires), or the
 *     countdown expires (hard-delete fires), or the component unmounts.
 *
 * WHY zustand (not React Context): UndoToast is a global fixed element. Zustand
 * selective subscription means only the UndoToast re-renders on state change,
 * not the entire page tree.
 */
import { create } from 'zustand'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** The kind of action that triggered the undo opportunity. */
export type UndoAction = 'complete' | 'delete'

/** The single active undo item. */
export interface UndoItem {
  /** The task id that was completed or deleted. */
  id: string
  /** The action that was performed (drives the undo toast message). */
  action: UndoAction
  /** The list the task belonged to (needed to invalidate the correct query). */
  listId: string
  /**
   * For recurring task completions: the next-instance id generated by the server.
   * Passed to undoTask so the server can also delete the next instance.
   * null for non-recurring tasks or plain deletes.
   */
  nextId: string | null
}

// ---------------------------------------------------------------------------
// Store shape
// ---------------------------------------------------------------------------

interface UndoState {
  /** The single active undo item, or null if no undo is pending. */
  activeItem: UndoItem | null

  /**
   * Show an undo opportunity. Replaces any existing active item (last-action-wins).
   * The caller is responsible for hard-deleting the replaced item immediately.
   */
  show: (item: UndoItem) => void

  /**
   * Clear the active undo item (call after undo fires or countdown expires).
   */
  clear: () => void
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useUndoStore = create<UndoState>((set) => ({
  activeItem: null,

  show: (item: UndoItem) => set({ activeItem: item }),

  clear: () => set({ activeItem: null }),
}))
